language: python
notifications:
  email: false
    # send all notifcations to slack
  slack: qcodes:tNlhSminOHdt2fZf6x6hyT24

python:
  - "3.4"
  # whitelist
branches:
  only:
    - master
# command to install dependencies
install:
    - pip install --upgrade pip
    - pip install ipython
    - pip install -r develop_requirements.txt
    - python setup.py develop
# command to run tests
script: 
    - python  qcodes/test.py --skip-coverage
    - python  qcodes/test.py --mp-spawn
after_success:
    # codecov
    - cd qcodes
    - coverage xml
    - python-codacy-coverage -r coverage.xml
    # codecvo
    - bash <(curl -s https://codecov.io/bash) -t c3b231db-2db3-4560-a477-6edcf4cf5ad1
    #
    # build the docs, one dir up
    - cd ../ 
    - make -f docs/Makefile gh-pages
