language: python
notifications:
  email: false
    # send all notifcations to slack
  slack: qcodes:tNlhSminOHdt2fZf6x6hyT24

cache: pip

python:
  - "3.5"
  # whitelist
branches:
  only:
    - master

# signal that we are on travis
# to disable things that expect an
# X Display
#
env:
    - TRAVISCI=true
# command to install dependencies
install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install coverage pytest-cov pytest --upgrade
    - pip install -e .
# command to run tests
script:
    - py.test --cov=qcodes --cov-report xml

after_success:
    # install codacy coverage plugin and sphinx only on traivs
    - pip install codacy-coverage sphinx sphinx_rtd_theme jsonschema sphinxcontrib-jsonschema
    - python-codacy-coverage -r coverage.xml
    # build the docs
    - make -f docs/Makefile gh-pages
